//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web
{
    public class HttpPostedFileBas
    {
        public string FileName { get; internal set; }

        internal void SaveAs(string v)
        {
            throw new NotImplementedException();
        }
    }
}